<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="INHYNSVUPPALA01" failures="1" tests="5" name="Personal loan" time="0.067" errors="0" timestamp="2025-01-09T10:52:20 IST">
  <testcase classname="Test.Day1" name="Demo" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Day1.Demo(Day1.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
at java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:132)
at java.base/java.util.concurrent.AbstractExecutorService.newTaskFor(AbstractExecutorService.java:113)
at java.base/java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:274)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="Test.Day2" name="Demo2" time="0.001"/>
  <testcase classname="Test.Day4" name="LoginAPIHomeLoan" time="0.0"/>
  <testcase classname="Test.Day4" name="MobileLoginHomeLoan" time="0.001"/>
  <testcase classname="Test.Day4" name="WebloginHomeLoan" time="0.001"/>
  <testcase classname="Test.Day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
